# Generated by Django 6.1 on 2026-08-10 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=16, unique=True)),
                ("timezone", models.CharField(default="Asia/Seoul", max_length=40)),
                ("working_hours_enabled", models.BooleanField(default=True)),
                ("working_hours_start", models.TimeField(default=datetime.time(9, 0))),
                ("working_hours_end", models.TimeField(default=datetime.time(18, 0))),
                ("onboarding_step", models.SmallIntegerField(default=0)),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
