# Generated by Django 6.1 on 2026-08-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="onboarding_completed_at",
        ),
    ]
