# Generated by Django 6.1 on 2026-08-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COMPANY', 'Company'), ('PROJECT', 'Project')], max_length=12)),
                ('area_key', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='companies.company')),
            ],
            options={
                'db_table': 'companies_scope',
            },
        ),
        migrations.CreateModel(
            name='HandbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body_ko', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('original_lang', models.CharField(default='ko', max_length=2)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('BLANK', 'Blank'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('confidence', models.CharField(blank=True, max_length=6, null=True)),
                ('origin', models.CharField(max_length=14)),
                ('ask_count', models.SmallIntegerField(default=0)),
                ('drift_status', models.CharField(choices=[('CURRENT', 'Current'), ('DRIFTED', 'Drifted')], default='CURRENT', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('embedding_ko', models.JSONField(blank=True, null=True)),
                ('embedding_en', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=40, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('translated_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbook_entries', to='companies.company')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbook_entries', to='handbook.companyscope')),
            ],
            options={
                'db_table': 'handbook_entry',
            },
        ),
        migrations.CreateModel(
            name='HandbookRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbook_revisions', to='companies.company')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='handbook.handbookentry')),
            ],
            options={
                'db_table': 'handbook_revision',
            },
        ),
    ]
