# Generated by Django 6.1 on 2026-08-11 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
        ('handbook', '0002_align_handbook_erd'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True, null=True)),
                ('locator', models.CharField(blank=True, max_length=60, null=True)),
                ('tag', models.CharField(max_length=8)),
                ('source_label', models.CharField(blank=True, max_length=200, null=True)),
                ('speaker_name', models.CharField(blank=True, max_length=60, null=True)),
                ('permalink', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbook_evidences', to='sources.chunk')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbook_evidences', to='companies.company')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbook_evidences', to='sources.rawdocument')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='handbook.handbookentry')),
            ],
            options={
                'db_table': 'handbook_evidence',
            },
        ),
    ]
