# Generated by Django 6.1 on 2026-08-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
        ('handbook', '0003_handbookevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyscope',
            name='area_key',
            field=models.CharField(blank=True, choices=[('COMPANY', 'Company'), ('PEOPLE', 'People'), ('PRODUCT_ENG', 'Product Eng'), ('SECURITY', 'Security')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='handbookentry',
            name='confidence',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='handbookentry',
            name='origin',
            field=models.CharField(choices=[('SLACK', 'Slack'), ('GITHUB', 'Github'), ('FILE', 'File'), ('ONBOARDING', 'Onboarding'), ('ESCALATION', 'Escalation'), ('DIRECT_ENTRY', 'Direct Entry')], max_length=16),
        ),
        migrations.AlterField(
            model_name='handbookevidence',
            name='tag',
            field=models.CharField(choices=[('SLACK', 'Slack'), ('GITHUB', 'Github'), ('NOTION', 'Notion'), ('FILE', 'File'), ('OWNER', 'Owner')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='companyscope',
            constraint=models.UniqueConstraint(fields=('company', 'area_key'), name='uniq_company_area_key'),
        ),
    ]
