# Generated by Django 6.1 on 2026-08-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
        ('handbook', '0005_seed_default_company_scopes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companyscope',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_company_scope_name'),
        ),
    ]
