# Generated by Django 6.1 on 2026-08-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0006_companyscope_uniq_company_scope_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookentry',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
