# Generated by Django 6.1 on 2026-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0009_day0_entry_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
