# Generated by Django 6.1 on 2026-08-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0010_handbookentry_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookentry',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
