# Generated by Django 6.1 on 2026-09-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0011_handbookentry_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookentry',
            name='auto_promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='auto_promotion_method',
            field=models.CharField(blank=True, choices=[('OWNER_DECISION', 'Owner Decision'), ('REPEATED_EVIDENCE', 'Repeated Evidence')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='conflict_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='detected_risk_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='evidence_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='promotion_policy_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='promotion_reason',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='promotion_type',
            field=models.CharField(choices=[('AUTO_PROMOTED', 'Auto Promoted'), ('PENDING_REVIEW', 'Pending Review'), ('MANUAL_REQUIRED', 'Manual Required')], db_index=True, default='PENDING_REVIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='similar_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_candidates', to='handbook.handbookentry'),
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
