# Generated by Django 6.1 on 2026-08-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'qna_citation',
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField(blank=True, null=True)),
                ('draft_ko', models.TextField(blank=True, null=True)),
                ('sent_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ANSWERED', 'Answered'), ('APPROVED', 'Approved'), ('DISMISSED', 'Dismissed')], default='DRAFT', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('slack_thread_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answer_is_answer', models.BooleanField(blank=True, null=True)),
                ('answer_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('answer_needs_review', models.BooleanField(default=False)),
                ('answer_ko', models.TextField(blank=True, null=True)),
                ('answer_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qna_escalation',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('AI', 'Ai')], max_length=4)),
                ('body_ko', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('GROUNDED', 'Grounded'), ('GROUNDED_BY_CASES', 'Grounded By Cases'), ('NO_SOURCE', 'No Source'), ('NEEDS_DECISION', 'Needs Decision'), ('OUT_OF_SCOPE', 'Out Of Scope')], max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=40, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=20, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('retrieval', models.JSONField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qna_message',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qna_thread',
            },
        ),
    ]
