# Generated by Django 6.1 on 2026-08-11 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
        ('handbook', '0001_initial'),
        ('qna', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_citations', to='sources.chunk'),
        ),
        migrations.AddField(
            model_name='citation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_citations', to='companies.company'),
        ),
        migrations.AddField(
            model_name='citation',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_citations', to='handbook.handbookentry'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='answer_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_escalations', to='sources.rawdocument'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qna_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_escalations', to='companies.company'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='proposed_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_escalations', to='handbook.handbookentry'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qna_escalations', to='handbook.companyscope'),
        ),
        migrations.AddField(
            model_name='message',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_messages', to='companies.company'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='origin_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation', to='qna.message'),
        ),
        migrations.AddField(
            model_name='citation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='qna.message'),
        ),
        migrations.AddField(
            model_name='thread',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_threads', to='companies.company'),
        ),
        migrations.AddField(
            model_name='thread',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qna_threads', to='handbook.companyscope'),
        ),
        migrations.AddField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qna_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='qna.thread'),
        ),
    ]
