# Generated by Django 6.1 on 2026-08-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
