# Generated by Django 6.1 on 2026-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_escalation_acknowledged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='proposed_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
