# Generated by Django 6.1 on 2026-08-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_escalation_proposed_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='reply_pending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
