# Generated by Django 6.1 on 2026-08-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_blank_answer_citations_blank_answered_by'),
        ('qna', '0005_escalation_reply_pending_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_threads', to='cards.instructioncard'),
        ),
    ]
