# Generated by Django 6.1 on 2026-08-10 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(choices=[('CAUTION', 'Caution'), ('DANGER', 'Danger')], default='CAUTION', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_keywords', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'keyword'), name='uniq_company_risk_keyword')],
            },
        ),
    ]
