# Generated by Django 6.1 on 2026-08-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(blank=True, max_length=40, null=True)),
                ('question_ko', models.TextField()),
                ('reason_text', models.CharField(blank=True, max_length=120, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('answer_ko', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_questions', to='companies.company')),
                ('created_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_questions', to='handbook.handbookentry')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_questions', to='handbook.companyscope')),
            ],
            options={
                'db_table': 'onboarding_question',
                'constraints': [models.UniqueConstraint(fields=('company', 'template_key'), name='uniq_question_template_key')],
            },
        ),
    ]
