# Generated by Django 6.1 on 2026-08-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('deliverable', models.TextField(blank=True, null=True)),
                ('deadline_text', models.CharField(blank=True, max_length=60, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('is_deadline_inferred', models.BooleanField(default=False)),
                ('tone_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('DONE', 'Done')], default='NEW', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cards_instructioncard',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.SmallIntegerField(default=0)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'cards_step',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=12)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('ord', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'cards_task',
            },
        ),
        migrations.CreateModel(
            name='ToneEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True, null=True)),
                ('outcome_note', models.CharField(blank=True, max_length=120, null=True)),
                ('source_label', models.CharField(blank=True, max_length=200, null=True)),
                ('permalink', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cards_toneevidence',
            },
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField()),
                ('sai_answer_en', models.TextField(blank=True, null=True)),
                ('sai_answer_ko', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_blanks', to='companies.company')),
            ],
            options={
                'db_table': 'cards_blank',
            },
        ),
    ]
