# Generated by Django 6.1 on 2026-08-11 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_initial'),
        ('companies', '0002_remove_company_onboarding_completed_at'),
        ('handbook', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructioncard',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruction_cards', to='sources.rawdocument'),
        ),
        migrations.AddField(
            model_name='instructioncard',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruction_cards', to='handbook.companyscope'),
        ),
        migrations.AddField(
            model_name='blank',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='cards.instructioncard'),
        ),
        migrations.AddField(
            model_name='step',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cards.instructioncard'),
        ),
        migrations.AddField(
            model_name='step',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_steps', to='companies.company'),
        ),
        migrations.AddField(
            model_name='step',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_steps', to='handbook.handbookentry'),
        ),
        migrations.AddField(
            model_name='task',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cards.instructioncard'),
        ),
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='companies.company'),
        ),
        migrations.AddField(
            model_name='task',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='handbook.companyscope'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toneevidence',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tone_evidences', to='cards.instructioncard'),
        ),
        migrations.AddField(
            model_name='toneevidence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tone_evidences', to='companies.company'),
        ),
        migrations.AddField(
            model_name='toneevidence',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tone_evidences', to='sources.rawdocument'),
        ),
    ]
