# Generated by Django 6.1 on 2026-08-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructioncard',
            name='deadline_text_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='instructioncard',
            name='deliverable_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructioncard',
            name='purpose_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructioncard',
            name='tone_note_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
