# Generated by Django 6.1 on 2026-08-15 08:14

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_instructioncard_deadline_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructioncard',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='cards.instructioncard'),
        ),
        migrations.AddField(
            model_name='instructioncard',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='instructioncard',
            name='urgency',
            field=models.CharField(choices=[('URGENT', 'Urgent'), ('SOON', 'Soon'), ('WHENEVER', 'Whenever'), ('UNCLEAR', 'Unclear')], default='UNCLEAR', max_length=8),
        ),
    ]
