# Generated by Django 6.1 on 2026-08-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_instructioncard_read_at_alter_instructioncard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='answer_citations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blank',
            name='answered_by',
            field=models.CharField(blank=True, choices=[('SAI', 'Sai'), ('OWNER', 'Owner')], max_length=5, null=True),
        ),
    ]
