# Generated by Django 6.1 on 2026-08-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_blank_answer_citations_blank_answered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructioncard',
            name='previous_column',
            field=models.CharField(blank=True, choices=[('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting'), ('ANSWERED', 'Answered'), ('DONE', 'Done')], max_length=12, null=True),
        ),
    ]
