# Generated by Django 6.1 on 2026-08-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("companies", "0002_remove_company_onboarding_completed_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="uniq_company_active_owner",
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True), ("role", "OWNER")),
                fields=("company",),
                name="uniq_company_active_owner",
            ),
        ),
        migrations.RemoveField(
            model_name="membership",
            name="status",
        ),
    ]
