# Generated by Django 6.1 on 2026-08-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_membership_uniq_company_active_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_role',
            field=models.CharField(blank=True, choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('DESIGN', 'Design'), ('PM', 'PM'), ('QA', 'QA'), ('DATA', 'Data')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_location',
            field=models.CharField(blank=True, choices=[('HANOI', 'Hanoi'), ('DA_NANG', 'Da Nang'), ('JAKARTA', 'Jakarta'), ('NEW_YORK', 'New York'), ('SEOUL', 'Seoul'), ('TOKYO', 'Tokyo')], max_length=10, null=True),
        ),
    ]
