# Generated by Django 6.1 on 2026-08-11 08:53

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
        ('handbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('GITHUB', 'Github'), ('SLACK', 'Slack'), ('NOTION', 'Notion'), ('LOCAL', 'Local')], max_length=10)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('ERROR', 'Error')], default='CONNECTED', max_length=12)),
                ('credential_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='companies.company')),
            ],
            options={
                'db_table': 'sources_connection',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=64)),
                ('external_handle', models.CharField(blank=True, max_length=120, null=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_identities', to='companies.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='sources.connection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sources_identity',
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('progress', models.SmallIntegerField(default=0)),
                ('item_ids', models.JSONField(blank=True, null=True)),
                ('entry_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='companies.company')),
            ],
            options={
                'db_table': 'sources_ingestionjob',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('is_scope_confirmed', models.BooleanField(default=False)),
                ('item_count', models.IntegerField(default=0)),
                ('storage_key', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_items', to='companies.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sources.connection')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_items', to='handbook.companyscope')),
            ],
            options={
                'db_table': 'sources_item',
            },
        ),
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ref', models.CharField(max_length=200)),
                ('thread_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('permalink', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('classified_as', models.CharField(choices=[('INSTRUCTION', 'Instruction'), ('CONTEXT', 'Context'), ('AMBIGUOUS', 'Ambiguous'), ('UNCLASSIFIED', 'Unclassified')], default='UNCLASSIFIED', max_length=14)),
                ('classifier_version', models.CharField(blank=True, max_length=20, null=True)),
                ('sync_state', models.CharField(choices=[('CURRENT', 'Current'), ('CHANGED', 'Changed'), ('REMOVED', 'Removed')], default='CURRENT', max_length=10)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('author_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sources.identity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_documents', to='companies.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sources.item')),
            ],
            options={
                'db_table': 'sources_rawdocument',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.SmallIntegerField(default=0)),
                ('text', models.TextField()),
                ('lang', models.CharField(default='ko', max_length=2)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=40, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('token_count', models.SmallIntegerField(default=0)),
                ('is_secret_filtered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='companies.company')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='handbook.companyscope')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sources.rawdocument')),
            ],
            options={
                'db_table': 'sources_chunk',
            },
        ),
        migrations.AddConstraint(
            model_name='identity',
            constraint=models.UniqueConstraint(fields=('connection', 'external_user_id'), name='uniq_identity_external_user'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='uniq_item_external_id'),
        ),
        migrations.AddConstraint(
            model_name='rawdocument',
            constraint=models.UniqueConstraint(fields=('item', 'external_ref'), name='uniq_document_external_ref'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_emb_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
