# Generated by Django 6.1 on 2026-08-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='bot_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='external_workspace_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='signing_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(condition=models.Q(('disconnected_at__isnull', True)), fields=('company', 'kind'), name='uniq_active_connection_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(condition=models.Q(('disconnected_at__isnull', True)), fields=('external_workspace_id',), name='uniq_active_workspace'),
        ),
    ]
