# Generated by Django 6.1 on 2026-08-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_connection_bot_token_connection_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='error_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
