# Generated by Django 6.1 on 2026-08-15 01:12

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_connection_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
