# Generated by Django 6.1 on 2026-08-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_alter_chunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='workspace_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
