# Generated by Django 6.1 on 2026-08-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
        ('handbook', '0007_handbookentry_reviewed_at'),
        ('sources', '0005_connection_workspace_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('document', 'ord'), name='uniq_chunk_document_ord'),
        ),
    ]
