# Generated by Django 6.1 on 2026-08-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_chunk_uniq_chunk_document_ord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
