# Generated by Django 6.1 on 2026-08-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_ingestionjob_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='card_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
