# Generated by Django 6.1 on 2026-08-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_rawdocument_card_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='kind',
            field=models.CharField(choices=[('COLLECT', 'Collect'), ('PROCESS', 'Process')], default='COLLECT', max_length=7),
        ),
    ]
