# Generated by Django 6.1 on 2026-08-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_ingestionjob_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='github_app_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='github_private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='github_webhook_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
