# Generated by Django 6.1 on 2026-08-17 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_connection_github_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to='sources.connection'),
        ),
    ]
