# Generated by Django 6.1 on 2026-08-17 05:51

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_onboarding_completed_at'),
        ('handbook', '0010_handbookentry_deleted_at'),
        ('sources', '0011_ingestionjob_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='embedding_en',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_en'], m=16, name='chunk_emb_en_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
