"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os, json, sys
from django.core.exceptions import ImproperlyConfigured
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

secret_file = BASE_DIR / 'secrets.json'
secrets = json.loads(secret_file.read_text()) if secret_file.exists() else {}


def get_secret(key, default=None):
    if key in os.environ:
        return os.environ[key]
    if key in secrets:
        return secrets[key]
    if default is not None:
        return default
    raise ImproperlyConfigured(f'{key} 설정이 없습니다')


def get_bool(key, default=False):
    value = get_secret(key, default)
    if isinstance(value, str):
        return value.strip().lower() in ('1', 'true', 'yes', 'on')
    return bool(value)


def get_list(key, default=None):
    value = get_secret(key, [] if default is None else default)
    if isinstance(value, str):
        return [item.strip() for item in value.split(',') if item.strip()]
    return list(value)


SECRET_KEY = get_secret('SECRET_KEY')

DEBUG = get_bool('DEBUG', False)

ALLOWED_HOSTS = get_list('ALLOWED_HOSTS', ['localhost', '127.0.0.1'])

CSRF_TRUSTED_ORIGINS = get_list('CSRF_ORIGINS', [])

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ( # DRF의 기본 인증Authentication 방식을 JWT로 바꿉니다.
        # 토큰을 확인하는 김에 마지막 접속 시각도 남긴다. 접속 중 표시가 여기에 기댄다.
        'accounts.authentication.LastSeenJWTAuthentication',
    ),
    # 기본: 인증 필수로 두고
    # 가입/로그인 뷰에서만 AllowAny로
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 에러 응답 : {"error": {"code", "field"}} 형태로 통일
    'EXCEPTION_HANDLER': 'config.exceptions.api_exception_handler',
    # rate_limited 에러용
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'signup': '5/min',
        'login': '10/min',
    },
}

SIMPLE_JWT = { # JWT 세부내용 설정
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=3),    # 유효기간 3시간
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # 유효기간 7일
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# Application definition

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
]

PROJECT_APPS = [
    'accounts',
    'companies',
    'policy',
    'handbook',
    'sources',
    'onboarding',
    'qna',
    'cards',
]

THIRD_PARTY_APPS = [
    'rest_framework_simplejwt',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
]


INSTALLED_APPS = DJANGO_APPS + PROJECT_APPS + THIRD_PARTY_APPS
AUTH_USER_MODEL = 'accounts.User'

CORS_ALLOWED_ORIGINS = get_list('CORS_ORIGINS', ['http://localhost:5173'])
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# DB 변경 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_secret('DB_NAME'),
        'USER': get_secret('DB_USER'),
        'PASSWORD': get_secret('DB_PASSWORD'),
        'HOST': get_secret('DB_HOST'),
        'PORT': get_secret('DB_PORT'),
    }
}

# drf-yasg (Swagger) 설정: Swagger UI에서 Bearer 토큰으로 인증 가능하도록 함
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
AWS_STORAGE_BUCKET_NAME = get_secret('S3_BUCKET', 'saisai-sources')
AWS_S3_REGION_NAME = 'ap-northeast-2'
SLACK_SIGNING_SECRET = get_secret('SLACK_SIGNING_SECRET')
SLACK_BOT_TOKEN = get_secret('SLACK_BOT_TOKEN')

# GitHub App 자격증명은 서버 환경변수(또는 secrets.json)에만 둔다.
# 심사자는 별도 GitHub 로그인 없이, 미리 설치해 둔 데모 레포 데이터를 조회한다.
GITHUB_APP_ID = get_secret('GITHUB_APP_ID', '')
GITHUB_PRIVATE_KEY = get_secret('GITHUB_PRIVATE_KEY', '')
GITHUB_INSTALLATION_ID = get_secret('GITHUB_INSTALLATION_ID', '')
GITHUB_WEBHOOK_SECRET = get_secret('GITHUB_WEBHOOK_SECRET', '')

# 키가 없어도 서버는 뜬다. 분류를 실행하는 시점에만 필요하고,
# 그때 ImproperlyConfigured로 실패하며 수집 결과는 그대로 남는다.
# 수집 작업을 요청 안에서 바로 돌린다. 워커(manage.py run_jobs)를 띄우기 번거로운
# 로컬에서만 켠다. 켜면 응답이 수십 초 걸린다.
INGESTION_RUN_INLINE = get_bool('INGESTION_RUN_INLINE', False)

OPENAI_API_KEY = get_secret('OPENAI_API_KEY', '')
# 분류는 라벨 하나만 고르면 되므로 저가 모델로 충분하다.
OPENAI_CLASSIFIER_MODEL = get_secret('OPENAI_CLASSIFIER_MODEL', 'gpt-4o-mini')
# 초안 작성은 여러 발언을 묶어 규칙 문장을 써야 해서 상위 모델을 쓴다.
OPENAI_DRAFTER_MODEL = get_secret('OPENAI_DRAFTER_MODEL', 'gpt-4o')
OPENAI_TRANSLATOR_MODEL = get_secret('OPENAI_TRANSLATOR_MODEL', 'gpt-4o-mini')
# 답변은 근거 안에서만 말하도록 절제해야 해서 상위 모델을 쓴다.
OPENAI_ANSWER_MODEL = get_secret('OPENAI_ANSWER_MODEL', 'gpt-4o')
OPENAI_ANSWER_REASONING_EFFORT = get_secret('OPENAI_ANSWER_REASONING_EFFORT', 'high')
OPENAI_ANSWER_VERBOSITY = get_secret('OPENAI_ANSWER_VERBOSITY', 'medium')
OPENAI_DRAFTER_REASONING_EFFORT = get_secret('OPENAI_DRAFTER_REASONING_EFFORT', 'high')
OPENAI_DRAFTER_VERBOSITY = get_secret('OPENAI_DRAFTER_VERBOSITY', 'medium')
OPENAI_TRANSLATOR_REASONING_EFFORT = get_secret('OPENAI_TRANSLATOR_REASONING_EFFORT', 'low')
OPENAI_TRANSLATOR_VERBOSITY = get_secret('OPENAI_TRANSLATOR_VERBOSITY', 'low')
OPENAI_CLASSIFIER_REASONING_EFFORT = get_secret('OPENAI_CLASSIFIER_REASONING_EFFORT', 'medium')
OPENAI_CLASSIFIER_VERBOSITY = get_secret('OPENAI_CLASSIFIER_VERBOSITY', 'low')
# 1536차원. handbook_entry.embedding_ko/en 과 sources_chunk.embedding 이 이 크기다.
OPENAI_EMBEDDING_MODEL = get_secret('OPENAI_EMBEDDING_MODEL', 'text-embedding-3-small')

# 핸드북 자동 승격 정책. 운영 중 기준을 바꿔도 과거 판단은 entry의 policy version으로 추적한다.
HANDBOOK_PROMOTION_POLICY_VERSION = get_secret(
    'HANDBOOK_PROMOTION_POLICY_VERSION', 'handbook-promotion-v1'
)
HANDBOOK_AUTO_PROMOTION_MIN_EVIDENCE = int(
    get_secret('HANDBOOK_AUTO_PROMOTION_MIN_EVIDENCE', 3)
)
HANDBOOK_AUTO_PROMOTION_RECENT_DAYS = int(
    get_secret('HANDBOOK_AUTO_PROMOTION_RECENT_DAYS', 30)
)
HANDBOOK_PROMOTION_SIMILAR_MAX_DISTANCE = float(
    get_secret('HANDBOOK_PROMOTION_SIMILAR_MAX_DISTANCE', 0.18)
)
HANDBOOK_PROMOTION_DUPLICATE_TEXT_RATIO = float(
    get_secret('HANDBOOK_PROMOTION_DUPLICATE_TEXT_RATIO', 0.90)
)

# 등록형 위험 키워드 외에 어떤 회사에서도 자동 확정하면 안 되는 공통 고위험 영역이다.
HANDBOOK_HIGH_RISK_KEYWORDS = {
    'SECURITY': ['보안', '암호', '비밀번호', '시크릿', '접근 권한', 'security', 'password', 'secret', 'credential'],
    'PRIVACY': ['개인정보', '개인 정보', '주민번호', '개인 데이터', 'privacy', 'personal data', 'pii'],
    'PAYMENT': ['결제', '정산', '환불', '카드 정보', 'payment', 'billing', 'refund', 'credit card'],
    'DEPLOYMENT': ['배포', '릴리스', '프로덕션', '운영 반영', 'deploy', 'deployment', 'release', 'production'],
    'PEOPLE': ['인사', '채용', '해고', '급여', '보상', '평가', '휴가', 'hr', 'hiring', 'termination', 'salary', 'compensation'],
}

# SDK 기본값은 timeout=600초, max_retries=2 다. 그대로 두면 호출 한 건이 최대 30분 매달린다.
# 워커는 단일 스레드라 그동안 큐 전체가 멈추고, STALE_AFTER(30분)와도 어긋난다.
OPENAI_TIMEOUT = float(get_secret('OPENAI_TIMEOUT', 30))
OPENAI_MAX_RETRIES = int(get_secret('OPENAI_MAX_RETRIES', 1))


# 워커가 무엇을 하다 멈췄는지는 로그로만 알 수 있다. 장고 기본 설정은 INFO 를 버린다.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'standard'},
    },
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {
        # 수집·카드·규칙 파이프라인. 여기가 INFO 여야 작업 시작과 끝이 남는다.
        app: {'handlers': ['console'], 'level': 'INFO', 'propagate': False}
        for app in ('sources', 'cards', 'handbook', 'qna', 'config')
    },
}

# 테스트는 일부러 실패를 만들어 보므로 그 로그가 결과를 덮는다.
if 'test' in sys.argv:
    LOGGING['root']['level'] = 'CRITICAL'
    for _logger in LOGGING['loggers'].values():
        _logger['level'] = 'CRITICAL'
